### ISSUE TITLE
Overlapping segments are not detected

### ISSUE THREAD

**Issue by anvaka** [ideasman42/isect_segments-bentley_ottmann#18]
I was playing with the library to see how it handles edge cases, and I stumbled upon this one, which doesn't seem to be right:

``` python
import poly_point_isect

print (
    poly_point_isect.isect_segments_include_segments(
        [
            ((0.0, 0.0),(10.000000, 10.000000)), 
            ((5.0, 5.0),(20.000000, 20.000000))
        ]
    )
)
```

The output is `[]`. I expected to see both `[5, 5]` and `[10, 10]`, but maybe I'm missing something?

**Comment by ideasman42** [comment]
This case is not handled.

However comparing all edges against all other edges also doesn't show any intersections in this case.

```
import poly_point_isect

print (
    poly_point_isect.isect_segments__naive([
        ((0.0, 0.0),(10.000000, 10.000000)),
        ((5.0, 5.0),(20.000000, 20.000000))
    ]))
```

Closing as this isn't a bug in the implementation.
