### ISSUE TITLE
[request] PyPI : pip installation packages

### ISSUE THREAD

**Issue by AND2797** [ideasman42/isect_segments-bentley_ottmann#21]
If possible, can the maintainers upload a `pip` installable package to PyPI? It would make importing and using the package more natural and smooth.

**Comment by ideasman42** [comment]
I don't see why not could you submit the setup.py and related files as a PR?

**Comment by AND2797** [comment]
Is there an existing PyPI page for this? If so can you link it to me?

**Comment by ideasman42** [comment]
Closing, as anything relating to pip packages can be handled in the PR.
